=== algethamy/fusio-impl/tests/Console/Schema/resource/export.json
{
  "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
  "id": "urn:schema.phpsx.org#",
  "definitions": {
    "Entry": {
      "type": "object",
      "title": "entry",
      "properties": {
        "id": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "type": "object",
  "title": "collection",
  "properties": {
    "totalResults": {
      "type": "integer"
    },
    "itemsPerPage": {
      "type": "integer"
    },
    "startIndex": {
      "type": "integer"
    },
    "entry": {
      "type": "array",
      "items": {
        "$ref": "#\/definitions\/Entry"
      }
    }
  }
}

=== algethamy/fusio-impl/tests/Controller/resource/human_collection.json
{
  "totalResults": 1,
  "startIndex": 0,
  "itemsPerPage": 16,
  "entry": [
    {
      "id": 1,
      "firstName": "Christoph",
      "lastName": "Kappestein",
      "location": {
        "id": 1,
        "name": "foo",
        "latitude": "50.883331",
        "longitude": "8.016667"
      },
      "tags": [
        "foo",
        "bar"
      ],
      "categories": [
        {
          "id": 1,
          "name": "foo"
        }
      ],
      "map": {
        "foo": {
          "id": 1,
          "name": "foo",
          "latitude": "50.883331",
          "longitude": "8.016667"
        },
        "bar": {
          "id": 1,
          "name": "foo",
          "latitude": "50.883331",
          "longitude": "8.016667"
        }
      }
    }
  ]
}
